### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by TrickJoker312** [Salty-Coder/Unblocked-Sites#2]
Hey! I noticed that you've forked my repository, and I appreciate that. I see that you're making your own unblocked sites repository as well, and i'd love to support! If you need any help, create an issue on my repository!

**Comment by TrickJoker312** [comment]
By the way, just.. uh... don't copy EVERYTHING from my repository. I've spent months looking for those sites, and I don't want anyone not realizing what I've done for the community. If you use about 20 or more, please credit me. Again, i'd love to support you on your journey of creating an Unblocked Site repository!

**Comment by bns34** [comment]
> By the way, just.. uh... don't copy EVERYTHING from my repository. I've spent months looking for those sites, and I don't want anyone not realizing what I've done for the community. If you use about 20 or more, please credit me. Again, i'd love to support you on your journey of creating an Unblocked Site repository!

Hi. I am planning for this repository to be a collection of existing repositories + sites I have found by myself. I plan to give full credit to all the sources of the sites I add to this repository so don't worry, I'll give you full credit as due.

**Comment by TrickJoker312** [comment]
alright, thanks! I appreciate it!

**Comment by bns34** [comment]
I have added the list now and given you credit.

**Comment by TrickJoker312** [comment]
Thanks! I appreciate it!
